# Compose file used in the dev container
name: user-service
services:
  user-service:
    build:
      context: .
    image: ghcr.io/thefunny42/user-service:main
    mem_reservation: 1g
    mem_limit: 4g
    environment:
      - AUTHORIZATION_ENDPOINT=http://opa:8181
      - DEFAULT_DATABASE_URL=mongodb://database:27017/users
    ports:
      - 8000:8000
  opa:
    image: openpolicyagent/opa:edge
    mem_reservation: 50m
    mem_limit: 100m
    command:
    - "run"
    - "--server"
    - "--set=decision_logs.console=true"
    - "/policies"
    ports:
      - 8181:8181
    volumes:
      - type: bind
        source: charts/userservice/policies
        target: /policies
  database:
    image: mongo:7-jammy
    mem_reservation: 300m
    mem_limit: 1g
    volumes:
      - database:/data/db
    ports:
      - 27017:27017
volumes:
  database:
