apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "userservice.fullname" . }}
data:
{{- if .Values.tags.opa }}
  authorization_endpoint: "http://{{ include "opa.fullname" .Subcharts.opa }}:{{ .Values.opa.service.port }}"
{{- else }}
  authorization_endpoint: "{{ .Values.authorizationEndpoint | required "Need an authorization endpoint" }}"
{{- end }}
{{- if .Values.tags.mongodb }}
  user_service_database: "mongodb://{{ include "mongodb.fullname" .Subcharts.mongodb }}:{{ .Values.mongodb.service.ports.mongodb }}/users"
{{- else }}
  user_service_database: "{{ .Values.databaseUrl | required "Need a database URL" }}"
{{- end }}
  user_service_issuer: {{ .Values.issuer }}
  user_service_audience: {{ .Values.audience }}
{{- if .Values.jwksUrl }}
  user_service_jwks_url: {{ .Values.jwksUrl }}
{{- end }}