apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "userservice.fullname" . }}
data:
  authorization-endpoint: "http://{{ include "opa.fullname" .Subcharts.opa }}:{{ .Values.opa.service.port }}"
  user-service-database: "mongodb://{{ include "mongo.fullname" .Subcharts.mongo }}:{{ .Values.mongo.service.port }}/users"
  user-service-issuer: {{ .Values.issuer }}
