apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "userservice.fullname" . }}
  labels:
    {{- include "userservice.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "userservice.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
{{- if and .Values.tags.opa .Values.tags.mongodb (not .Values.jwksUrl) }}
  - Egress
{{- end}}
  ingress:
  - ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
{{- if and .Values.tags.opa .Values.tags.mongodb (not .Values.jwksUrl) }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- include "opa.selectorLabels" .Subcharts.opa | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.opa.service.port}}
  - to:
    - podSelector:
        matchLabels:
          {{- include "common.labels.matchLabels" .Subcharts.mongodb | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.mongodb.service.ports.mongodb}}
{{- end }}