{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "userservice.fullname" .) }}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "userservice.fullname" . }}
type: Opaque
data:
  key: {{ .Values.key | b64enc }}
{{- end }}
