{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "userservice.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "userservice.fullname" . }}
type: Opaque
data:
{{- if $existingSecret }}
  key: {{ index $existingSecret.data "key" }}
{{- else }}
  key: {{ default (randAlphaNum 32) .Values.key | b64enc | quote }}
{{- end }}
