name: Test policies and build charts
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      - name: Code Analysis
        working-directory: charts/opa/policies
        run: opa fmt --diff --fail .
      - name: Test
        working-directory: charts/opa/policies
        run: opa test -v .
  release:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          path: .repository
          repository: thefunny42/charts
          persist-credentials: true
          token: "${{ secrets.CHART_TOKEN }}"
          ref: main
      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Release charts
        run: |
          for chart in $(ls charts); do
            helm dependency update charts/$chart;
            helm lint charts/$chart;
            helm package charts/$chart -d .repository;
          done
          helm repo index .repository/ --url https://thefunny42.github.io/charts
          cd .repository
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add index.yaml *.tgz
          git commit -m 'Update charts'
          git push origin main
